# Generated by Django 4.0.6 on 2022-07-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='commentcount',
            field=models.IntegerField(),
        ),
    ]
