# Generated by Django 4.0.6 on 2022-07-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookinfo_commentcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='book_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book.bookinfo'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='description',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personinfo',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
