# Generated by Django 4.0.6 on 2022-07-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_personinfo_book_id_personinfo_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personinfo',
            table='personinfo',
        ),
    ]
