# Generated by Django 4.0.6 on 2022-07-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_personinfo_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personinfo',
            old_name='book_id',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'male'), (2, 'female')], default=1),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
