# Generated by Django 4.0.6 on 2022-07-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'verbose_name': 'bookinfo'},
        ),
        migrations.AlterModelOptions(
            name='peopleinfo',
            options={'verbose_name': 'peopleinfo'},
        ),
    ]
